<a href="https://colab.research.google.com/github/Edd17369/Algorithms/blob/master/NReinas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problema de las N-Reinas

## a) Codificación entera

In [99]:
import itertools
from collections import Counter
import random
import numpy as np

tam_poblacion = 10
num_generaciones = 1000
prob_cruza = 0.8
prob_mutacion = 0.03
n=10


# permutaciones
numeros = list(range(1,n+1))
muestra_permutaciones = random.sample(list(itertools.permutations(numeros)), tam_poblacion)

# aptitud
def fitness_individuo(individuo_gen):
  """
  Dado un individuo calcula su número de coliciones
  """
  n = len(individuo_gen)
  coliciones = 0
  for i in range(n):
    for j in range(i+1,n):
      if abs(i-j) == abs(individuo_gen[i]-individuo_gen[j]):
        coliciones += 1
  return coliciones

def fitness(poblacion):
  """
  Calcula la aptitud para todos los individuos de la poblacion y los ordena segun esta
  """
  for individuo in poblacion:
      individuo.aptitud = fitness_individuo(individuo.genotipo)
  poblacion.sort(key=lambda x: x.aptitud)  



# Individuos
class Individuo:
    def __init__(self, genotipo):
        self.genotipo = genotipo
        self.aptitud = None



# Seleccion por ruleta
def ruleta(poblacion):
    fitness_total = sum([ind.aptitud for ind in poblacion])
    seleccionados = []
    for i in range(len(poblacion)):
        r = np.random.uniform(0, fitness_total)
        acumulado = 0
        for ind in poblacion:
            acumulado += ind.aptitud
            if acumulado > r:
                seleccionados.append(ind)
                break
    return seleccionados


# Cruza (single point)
def cruza(padre1, padre2):
    n = len(padre1.genotipo)
    pnt_cruza = np.random.randint(1, n)
    gen1 = np.concatenate((padre1.genotipo[:pnt_cruza], padre2.genotipo[pnt_cruza:]), axis=0)
    gen2 = np.concatenate((padre2.genotipo[:pnt_cruza], padre1.genotipo[pnt_cruza:]), axis=0)
  
    for gen in [gen1, gen2]:
      disponibles = list(set(range(1,n+1)).difference(set(gen)))
      new_gen = []
      for x in gen:
        if x not in new_gen:
          new_gen.append(x)
        else:
          new_gen.append(disponibles.pop(0))
      gen = new_gen

    hijo1 = Individuo(gen1)
    hijo2 = Individuo(gen2)
    return hijo1, hijo2


# Mutación
def mutacion(poblacion, prob_mutacion): 
  for individuo in poblacion:
    if np.random.uniform(0, 1) < prob_mutacion:
      pnts = np.random.randint(0, len(individuo.genotipo), size=2, dtype=int)
      new_genotipo = list(individuo.genotipo)
      new_genotipo[pnts[0]], new_genotipo[pnts[1]] = new_genotipo[pnts[1]], new_genotipo[pnts[0]]
      individuo.genotipo = new_genotipo
    else:
      continue




# Inicializa la poblacion
poblacion = []
for _ in muestra_permutaciones:
  poblacion.append(Individuo(_))

fitness(poblacion)
generacion = 1


"""
fitness(poblacion)
mutacion(poblacion, prob_mutacion)
[(ind.genotipo, ind.aptitud) for ind in poblacion] 
seleccionados = ruleta(poblacion[1:])

[(ind.genotipo, ind.aptitud) for ind in seleccionados] 
"""

'\nfitness(poblacion)\nmutacion(poblacion, prob_mutacion)\n[(ind.genotipo, ind.aptitud) for ind in poblacion] \nseleccionados = ruleta(poblacion[1:])\n\n[(ind.genotipo, ind.aptitud) for ind in seleccionados] \n'

In [96]:
x = Individuo([ 8, 4,  2,  8,  6,  1,  3,  6,  6, 10])

fitness_individuo(x.genotipo)

0

In [100]:
while (generacion < num_generaciones) and (poblacion[0].aptitud != 0):
  # elitismo del mejor individuo
  hijos = [poblacion[0]]
  seleccionados = poblacion #ruleta(poblacion[1:])
      
  while len(hijos) < tam_poblacion:
    i, j = np.random.randint(0, len(seleccionados), size=2, dtype=int)
    if random.random() < prob_cruza:
        hijos += cruza(seleccionados[i], seleccionados[j])
    else:
        hijos += [seleccionados[i], seleccionados[j]]

  poblacion = hijos
  #mutacion(poblacion, prob_mutacion)
  fitness(poblacion)
  generacion += 1
  
    
  print(poblacion[0].genotipo, poblacion[0].aptitud, generacion)


(9, 4, 1, 7, 5, 3, 2, 10, 8, 6) 3 2
[ 7  6  1  7  5  3  2 10  8  6] 2 3
[ 7  6  1  7  5  3  2 10  8  6] 2 4
[ 7  6  1  7  5  3  2 10  8  6] 2 5
[ 7  6  1  7  5  3  2 10  8  6] 2 6
[ 7  6  1  7  5  3  2 10  8  6] 2 7
[ 7  6  1  7  5  3  2 10  8  6] 2 8
[ 7  6  1  7  5  3  2 10  8  6] 2 9
[ 7  6  1  7  5  3  2 10  8  6] 2 10
[ 7  6  1  7  5  3  2 10  8  6] 2 11
[ 7  6  1  7  5  3  2 10  8  6] 2 12
[ 7  6  1  7  5  3  2 10  8  6] 2 13
[ 7  6  1  7  5  3  2 10  8  6] 2 14
[ 7  6  1  7  5  3  2 10  8  6] 2 15
[ 7  6  1  7  5  3  2 10  8  6] 2 16
[ 7  6  1  7  5  3  2 10  8  6] 2 17
[ 7  6  1  7  5  3  2 10  8  6] 2 18
[ 7  6  1  7  5  3  2 10  8  6] 2 19
[ 7  6  1  7  5  3  2 10  8  6] 2 20
[ 7  6  1  7  5  3  2 10  8  6] 2 21
[ 7  6  1  7  5  3  2 10  8  6] 2 22
[ 7  6  1  7  5  3  2 10  8  6] 2 23
[ 7  6  1  7  5  3  2 10  8  6] 2 24
[ 7  6  1  7  5  3  2 10  8  6] 2 25
[ 7  6  1  7  5  3  2 10  8  6] 2 26
[ 7  6  1  7  5  3  2 10  8  6] 2 27
[ 7  6  1  7  5  3  2 10  8  6] 2 28
[ 7  6  1